name: keep-caroney-awake
on:
  schedule:
    - cron: "0 */12 * * *"   # cada 12 horas
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl app
        run: |
          curl -sSfL "$APP_URL" -o /dev/null
        env:
          APP_URL: "https://caroney.streamlit.app/"
